"""Training registry."""
from ..models import TrainingModule

TRAINING_MODULES = [
    TrainingModule(
        module_id="foundations",
        title="量子网络基础",
        tier=1,
        category="learning",
        base_success=0.9,
        cost=300,
        hours=3,
        skill_gain={"foundation": 1},
        description="巩固TCP/IP、Linux与脚本基础，为任何方向铺路。",
    ),
    TrainingModule(
        module_id="web_scope",
        title="Web渗透侦察",
        tier=1,
        category="learning",
        base_success=0.75,
        cost=600,
        hours=5,
        skill_gain={"web": 1},
        description="掌握前端、后台常见漏洞足迹与自动化扫描。",
    ),
    TrainingModule(
        module_id="bin_boot",
        title="二进制破冰",
        tier=2,
        category="learning",
        base_success=0.55,
        cost=1200,
        hours=8,
        skill_gain={"binary": 1},
        description="逆向思维、寄存器与栈溢出的第一课。",
    ),
    TrainingModule(
        module_id="social_mesh",
        title="高级社会工程",
        tier=2,
        category="learning",
        base_success=0.62,
        cost=900,
        hours=6,
        skill_gain={"social": 1},
        description="针对高管和客服的多阶段钓鱼剧本演练。",
    ),
    TrainingModule(
        module_id="cloud_core",
        title="云渗透核心",
        tier=3,
        category="learning",
        base_success=0.48,
        cost=1800,
        hours=9,
        skill_gain={"cloud": 1},
        description="熟悉IAM滥用、元数据窃取与容器脱逃链。",
    ),
]
